### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by sibalaxiii** [zhangjk95/MahjongAI#10]
打了两百个半庄 默认和防守重视各一百把 防守模式胡牌率24 默认27 而放铳率竟然都在16左右
所以比较好奇 这两个模式在算法上的异同

**Comment by zhangjk95** [comment]
其实"Default"是最保守的策略。"Default"会防御立直家、三副露牌河6张、两副露牌河9张、一副露牌河12张的玩家， "DefendReachedPlayers"只防立直家，"DefendReachedOya"只防立直亲家。可能我在注释里没有写清楚，下个版本会对注释进行改进。

放铳率都在16左右这件事比较奇怪，我自己用"Default"进行尝试的时候放铳率都在12-14左右。

**Comment by sibalaxiii** [comment]
原来如此 以下是全程只防立直家 低分段的战绩
![image](https://user-images.githubusercontent.com/49758370/58739780-c0438500-843e-11e9-9b64-bd117be3fc71.png)
全程默认的号找不到了。。但是我清楚记得放铳率不会低于16
还是觉得铳率略高了些 算法上不知道是否有改进的余地

**Comment by zhangjk95** [comment]
16的铳率确实高得离谱了，我实测没有遇到过这个情况，请确认以下几点：
1. 更改App.config后请在VS中点击绿色三角来运行程序，不要双击exe打开，否则更改的配置不会生效。
1. 运行的选项请选择Release而不是Debug。Debug会导致速度太慢使得有时会超时自动模切。
2. 如果你用的是笔记本电脑，请接上电源并将电源配置设置为“最佳性能”（在屏幕右下角的电池图标处设置）否则会导致速度太慢使得有时会超时自动模切。

**Comment by zhangjk95** [comment]
Documentation updated by https://github.com/zhangjk95/MahjongAI/commit/68c9165a441fb98fa7ed7f08d1685e0e7350a294

**Comment by zhangjk95** [comment]
非常抱歉！我发现我5个月前的一次改动中改出了巨大bug，导致铳率突然升高。目前该bug已修复，最新版本中应该不会有这个情况。
