### ISSUE TITLE
连接异常

### ISSUE THREAD

**Issue by sibalaxiii** [zhangjk95/MahjongAI#11]
![image](https://user-images.githubusercontent.com/49758370/58757699-5365e300-8543-11e9-8b4e-c43470594476.png)

**Comment by Anego777** [comment]
把MajsoulClient.cs的21行和22行的lb-hk.majsoul.com:7891改成lb-mainland.majsoul.com:2901就可以了

**Comment by sibalaxiii** [comment]
> 把MajsoulClient.cs的21行和22行的lb-hk.majsoul.com:7891改成lb-mainland.majsoul.com:2901就可以了

多谢

**Comment by zhangjk95** [comment]
下个版本会加入线路的选择

**Comment by zhangjk95** [comment]
Fixed by https://github.com/zhangjk95/MahjongAI/commit/33d151e1d664195a2482d81c0f637af2b5fe2340
