### ISSUE TITLE
这是不是太激进了？

### ISSUE THREAD

**Issue by Anego777** [zhangjk95/MahjongAI#13]
![QQ图片20190603145737](https://user-images.githubusercontent.com/26843124/58782217-8de98180-8610-11e9-88c6-950eb1da823a.png)
从听14p变成了听36p...不论西是不是役牌都不应该碰啊，听牌强度降低，有人立直也少了3张安牌

**Comment by Anego777** [comment]
碰西后跳符了...不过要说全力防守...根据向听数、得点期望和进张数来决定是否防守还是有点对日的意思
`       private bool shouldDef4(EvalResult evalResult, Tile discardTile = null)
        {
            return evalResult.Distance >= 3
                || evalResult.Distance == 2 && (
                    evalResult.E_Point < 8000
                    || evalResult.E_PromotionCount[0] <= 15 && evalResult.E_Point < 12000
                    || evalResult.E_PromotionCount[0] <= 8)
                || evalResult.Distance == 1 && (
                    (evalResult.E_Point < 2000 && isTileTooDangerous(discardTile))
                    || (evalResult.E_PromotionCount[0] <= 20 && evalResult.E_Point < 4000)
                    || (evalResult.E_PromotionCount[0] <= 9 && evalResult.E_Point < 8000)
                    || evalResult.E_PromotionCount[0] <= 4)
                || evalResult.Distance == 0 && (evalResult.E_Point < 2000 || evalResult.E_PromotionCount[0] < 1) && isTileTooDangerous(discardTile)
                || gameData.remainingTile / 4 <= evalResult.Distance * 2 && isTileTooDangerous(discardTile);
        } 
		
        private bool shouldDef2(EvalResult evalResult, Tile discardTile = null)
        {
            return evalResult.Distance >= 3
                || evalResult.Distance == 2 && (
                    evalResult.E_Point < 4000
                    || evalResult.E_PromotionCount[0] <= 15 && evalResult.E_Point < 12000
                    || evalResult.E_PromotionCount[0] <= 8)
                || evalResult.Distance == 1 && (
                    (evalResult.E_Point < 1000 && isTileTooDangerous(discardTile))
                    || (evalResult.E_PromotionCount[0] <= 20 && evalResult.E_Point < 2000)
                    || (evalResult.E_PromotionCount[0] <= 9 && evalResult.E_Point < 8000)
                    || evalResult.E_PromotionCount[0] <= 4)
                || evalResult.Distance == 0 && (evalResult.E_Point < 1000 || evalResult.E_PromotionCount[0] < 1) && isTileTooDangerous(discardTile)
                || gameData.remainingTile / 4 <= evalResult.Distance * 2 && isTileTooDangerous(discardTile);
        } 

        private bool shouldDef1(EvalResult evalResult, Tile discardTile = null)
        {
            // 最后三巡
            return evalResult.Distance >= 2;
        } 
`
我是改成了
`		private bool shouldDef4(EvalResult evalResult, Tile discardTile = null)
        {
            return player.point >= 30000
	        || evalResult.Distance >= 1 
                || evalResult.Distance == 0 && (evalResult.E_Point < 4000 || evalResult.E_PromotionCount[0] < 1) && isTileTooDangerous(discardTile)
                || gameData.remainingTile / 4 <= evalResult.Distance * 2 && isTileTooDangerous(discardTile);
        }
		
		private bool shouldDef2(EvalResult evalResult, Tile discardTile = null)
        {
            return player.point >= 30000
		|| evalResult.Distance >= 1 
                || evalResult.Distance == 0 && (evalResult.E_Point < 4000 || evalResult.E_PromotionCount[0] < 1) && isTileTooDangerous(discardTile)
                || gameData.remainingTile / 4 <= evalResult.Distance * 2 && isTileTooDangerous(discardTile);
        }

		private bool shouldDef1(EvalResult evalResult, Tile discardTile = null)
        {
            // 最后三巡
            return player.point >= 30000
			    || evalResult.Distance >= 1
			    || evalResult.Distance == 0 && isTileTooDangerous(discardTile);
				
        }`

**Comment by zhangjk95** [comment]
确实是根据向听数、得点期望和进张数来决定是否防守。我指的全力防守的意思是，一旦某一手决定防守，就会把牌拆得很散，很难像人类一样考虑兜牌的空间。因此我对防守加了很多条件限制，使得总体上策略是偏对日的。
这个AI在牌效上比同等水平的人类有较大优势，但混合策略（留安、兜牌等）不行，而且也不太会看点差打牌（AL除外），因此选择偏进攻的策略来尽可能地发挥AI的优势，而不是模拟人类打牌的方法。当然如果你有实测下来更好的防守条件，欢迎提出。

**Comment by zhangjk95** [comment]
非常抱歉！我发现我5个月前的一次改动中改出了巨大bug，导致铳率突然升高。目前该bug已修复，最新版本中应该不会有这个情况。https://github.com/zhangjk95/MahjongAI/commit/854793132387ee8dfcd90603a16813164ce9baa8
