### ISSUE TITLE
大三元大四喜规则能不能优化下？

### ISSUE THREAD

**Issue by asd976385560** [zhangjk95/MahjongAI#16]
麻烦看图，谢谢。
[http://m.qpic.cn/psb?/V13HYJgT3QbPIk/BPuXwaKiED*gYs0H99sJBO4Ly1eGpPuXcHk7gyOIMVM!/b/dPMAAAAAAAAA&bo=5QTwAgAAAAARFzM!&rf=viewer_4](url)
白发全是自己丢的  最后竟然还丢了个中送役满,3w2直接被飞了
对于大三元大四喜能不能加个规则，确定场上同一家有2-3个碰后不在打这些牌，不然当场去世。。。

这个能不能加个规则优化下呢？

**Comment by asd976385560** [comment]
http://a4.qpic.cn/psb?/V13HYJgT3QbPIk/BPuXwaKiED*gYs0H99sJBO4Ly1eGpPuXcHk7gyOIMVM!/b/dPMAAAAAAAAA&ek=1&kp=1&pt=0&bo=5QTwAgAAAAARFzM!&tl=3&vuin=976385560&tm=1564272000&sce=60-1-1&rf=viewer_4

**Comment by zhangjk95** [comment]
抱歉一直忘记回复。这个理论上是可以做到的，但是我不太希望再加入新的规则。由于这个AI并不依赖于机器学习，所有操作都是基于一定的规则来判断得出的，导致目前规则已经过于复杂，加入更多的规则可能会导致代码难以维护。对于这个AI我的期望是能在大部分正常情况下做出合理的操作就可以了，至于役满等不太常见的情况我没有计划做特殊的处理，抱歉。
