### ISSUE TITLE
关于两局之间间隔的建议

### ISSUE THREAD

**Issue by fj233** [zhangjk95/MahjongAI#19]
建议每两局之间能够设置有随机的间隔时间，以减少被ban的几率。
另外，现在每局结束之后会退出游戏然后重进，可否添加一个选项，使玩家能够决定一局之后是否退出游戏?

**Comment by fj233** [comment]
另外，建议进入游戏到开始一局的这段时间内也加入随机延时

**Comment by zhangjk95** [comment]
如果这么做的目的只是为了使操作显得“更像人类”的话，那我觉得是没有意义的，原因是AI除了间隔时间外还有太多方面和人类的操作有区别，详细讨论见https://github.com/zhangjk95/MahjongAI/issues/9#issuecomment-494451630

关于每局结束后是否退出的选项，这个一直是存在的。在一局进行的过程中随时可以按下“q”并回车，这局结束后就会自动退出。这个选项在界面上没有提示，但是在App.config里是提到的。

**Comment by fj233** [comment]
非常感谢你能解决我的疑惑。
但是，可能我表达的不是很清楚，我所说的“退出游戏”指的是在每局游戏完成之后会退出账号并重新登陆，无论是连续打几盘都会有这种情况发生，可否添加一个选项使得一盘游戏结束后不退出账号而是直接开启下一盘呢？

**Comment by zhangjk95** [comment]
这个理论上是可以的，但是我觉得没有必要，毕竟从效果上来看是一样的，同样开始了新的游戏，同样和人类的操作有区别。

**Comment by Eureka0225** [comment]
其实是可以让ai不下线直接开下一盘的



------------------ 原始邮件 ------------------
发件人: "Jiakai Zhang"<notifications@github.com>; 
发送时间: 2019年8月31日(星期六) 下午2:53
收件人: "zhangjk95/MahjongAI"<MahjongAI@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [zhangjk95/MahjongAI] 关于两局之间间隔的建议 (#19)



这个理论上是可以的，但是我觉得没有必要，毕竟从效果上来看是一样的，同样开始了新的游戏，同样和人类的操作有区别。
