### ISSUE TITLE
有报错诶MahjongAI.exe Error: 0 : System.ArgumentNullException: 值不能为 null。

### ISSUE THREAD

**Issue by asd976385560** [zhangjk95/MahjongAI#20]
这个报错也不是很长见。。。
我用的VS2019编译的。

[13:50:26] 游戏结束.
MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":".lq.NotifyGameFinishReward","Json":{"mode_id":9,"level_change":{"origin":{"id":10401,"score":1172},"final":{"id":10401,"score":1280}},"match_chest":{"chest_id":2,"origin":380,"final":740,"is_graded":false},"main_character":{"level":4,"exp":14740,"add":60}},"Data":null}
MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":".lq.NotifyActivityReward","Json":{},"Data":null}
MahjongAI.exe Information: 0 : Recv: {"Success":false,"Type":0,"MethodName":null,"Json":null,"Data":"010A172E6C712E4E6F746966794163746976697479506F696E741200"}

MahjongAI.exe Error: 0 : System.ArgumentNullException: 值不能为 null。
参数名: key
   在 System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   在 System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   在 MahjongAI.MajsoulClient.HandleMessage(MajsoulMessage message, Boolean forSync)
   在 MahjongAI.MajsoulClient.<OnMessage>d__54.MoveNext()

MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.heatbeat","Json":{"error":{}},"Data":null}
MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.heatbeat","Json":{"error":{}},"Data":null}
[13:50:36] 客户端关闭.

**Comment by zhangjk95** [comment]
我有空看一下

**Comment by zhangjk95** [comment]
Fixed by https://github.com/zhangjk95/MahjongAI/commit/65e7d9d4beedf8a77678e8b6abe41669c724cc71.

**Comment by zhangjk95** [comment]
另外请问这个中文版的来源是？

**Comment by asd976385560** [comment]
有耐心的人给翻译了一下，需要源码吗？可以给你一份

**Comment by asd976385560** [comment]
链接：https://pan.baidu.com/s/1z5DDRF6yNRvhe8K3JJT6Uw 
提取码：hbdx
