### ISSUE TITLE
In Docker ,It cant be build now?

### ISSUE THREAD

**Issue by endlessWar** [zhangjk95/MahjongAI#23]
![image](https://user-images.githubusercontent.com/47861644/65126065-350bf080-da29-11e9-9444-7d0873044e1c.png)
No message return...

**Comment by re-div** [comment]
可以尝试分开执行 `build.sh` 中的两句代码。

**Comment by endlessWar** [comment]
![image](https://user-images.githubusercontent.com/47861644/65310282-91554880-dbc0-11e9-92bd-fc0d26b99fea.png)
就是第一句执行后没反应，docker中会多一个运行中的gcc容器，然后就没有反应了

**Comment by zhangjk95** [comment]
可能是gcc的image没有下载成功，可以试试`docker pull gcc:4.9`看看有没有反应，成功的话再运行`build.sh`。不过要提示一下，这个项目已经不再支持雀魂了，如果你想在雀魂上运行，这个项目可能对你并没有帮助。
