### ISSUE TITLE
不能正常用

### ISSUE THREAD

**Issue by 1212march** [zhangjk95/MahjongAI#29]
登录成功之后 总是说匹配超时然后重连
`

> Login succeeded.
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":".lq.NotifyAccountUpdate","Json":{"update":{"activity_task":{"progresses":[{"id":1031025,"counter":1,"achieved":true,"rewarded":false},{"id":1031026,"counter":10,"achieved":true,"rewarded":false},{"id":1031027,"counter":1,"achieved":false,"rewarded":false}]}}},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.matchGame","Json":{"error":{}},"Data":null}
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.heatbeat","Json":{"error":{}},"Data":null}
> Game matching timed out.
> Unexpectedly disconnected.
> Client closed.Login succeeded.
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":".lq.NotifyAccountUpdate","Json":{"update":{"activity_task":{"progresses":[{"id":1031025,"counter":1,"achieved":true,"rewarded":false},{"id":1031026,"counter":10,"achieved":true,"rewarded":false},{"id":1031027,"counter":1,"achieved":false,"rewarded":false}]}}},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.matchGame","Json":{"error":{}},"Data":null}
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.heatbeat","Json":{"error":{}},"Data":null}
> Game matching timed out.
> Unexpectedly disconnected.
> Client closed.

`

咱还不信邪啊  在网页端开了一局之后  想让它重连进去 结果还是不行 

> Login succeeded.
> Game found. Connecting...
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.FastTest.authGame","Json":null,"Data":{"account_id":8447372,"token":"c4b8d64e-621f-4cb4-8c47-c4968da822f2","game_uuid":"200108-b57d8755-e05f-4621-b063-504ec02221b1"}}
> MahjongAI.exe Information: 0 : Recv: {"Success":false,"Type":1,"MethodName":".lq.FastTest.authGame","Json":null,"Data":"0301000A00129903127708BBEB461099C61818CACF242215E381B5E3818FE38198E781ACE381BFE381BBE381932A0608D94F109901320E08D69A0C100518002899C61830003A0608859D011000400048005206080010EACE125206080110EFCE125206080210FECE12520608041081CF125206080710F8CE125206080810BADE1212730897FF1C10E8B51818CBCF24220CE7A59EE58C97E58D83E6ADA22A0608D94F108703321308C19A0C100418B42E28E8B51830003A02E4073A0608859D01100040004800520608001084CF125206080110FFCE125206080210F2CE12520608041082CF12520608061096CF125206080710F9CE12123A08BED0D40710E5B5181800220AE7A791E7A791E7A791782A0508F54E1000320E08C19A0C1000180028E5B51830003A0608859D01100040004800123D088CCB830410E5B51818C8CF24220A61313231326D617263682A0508F74E1014320F08C19A0C100418885928E5B51830003A0608859D011000400048001A0E8CCB830497FF1CBED0D407BBEB4620012A0C08021204080132001A021002320E8CCB830497FF1CBED0D407BBEB46"}
> Game continued.
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.FastTest.syncGame","Json":null,"Data":{"round_id":"-1","step":1000000}}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.FastTest.syncGame","Json":{"error":{},"is_end":false,"step":6,"game_restore":{"actions":[{"step":0,"name":"ActionMJStart","data":""},{"step":1,"name":"ActionNewRound","data":"CAAQABgAIgI1bSICNm0iAjhtIgI0cCICNXAiAjJzIgIzcyICNXMiAjdzIgI5cyICNXoiAjZ6IgI2eiICN3oyDKjDAajDAajDAajDAToNCAASAggBIKCcASjAPkAAWABiIDFkM2UwMzI3OTEyYTU4NWY5NDNiN2ExNzU1YWY2MTljaEVyAjVtegIIAHoCCAF6AggCegIIAw=="},{"step":2,"name":"ActionDiscardTile","data":"CAASAjlzGAAoADAASAA="},{"step":3,"name":"ActionDealTile","data":"CAEYRDgA"},{"step":4,"name":"ActionDiscardTile","data":"CAESAjJwGAAoADAASAA="},{"step":5,"name":"ActionDealTile","data":"CAIYQzgA"}],"passed_waiting_time":4,"game_state":1,"last_pause_time_ms":0}},"Data":null}
> MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.FastTest.fetchGamePlayerState","Json":null,"Data":{}}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionMJStart","Json":{},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionNewRound","Json":{"chang":0,"ju":0,"ben":0,"tiles":["5m","6m","8m","4p","5p","2s","3s","5s","7s","9s","5z","6z","6z","7z"],"scores":[25000,25000,25000,25000],"operation":{"seat":0,"operation_list":[{"type":1}],"time_add":20000,"time_fixed":8000},"liqibang":0,"al":false,"md5":"1d3e0327912a585f943b7a1755af619c","left_tile_count":69},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDiscardTile","Json":{"seat":0,"tile":"9s","is_liqi":false,"moqie":false,"zhenting":false,"is_wliqi":false},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDealTile","Json":{"seat":1,"left_tile_count":68,"zhenting":false},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDiscardTile","Json":{"seat":1,"tile":"2p","is_liqi":false,"moqie":false,"zhenting":false,"is_wliqi":false},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDealTile","Json":{"seat":2,"left_tile_count":67,"zhenting":false},"Data":null}
> MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.FastTest.fetchGamePlayerState","Json":{"error":{},"state_list":[null,null,"SYNCING","READY","READY","READY"]},"Data":null}
> MahjongAI.exe Error: 0 : System.NullReferenceException: 未将对象引用设置到对象的实例。
>    在 MahjongAI.Models.Tile.<>c__DisplayClass5_0.<.ctor>b__0(KeyValuePair`2 pair) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\Models\Tile.cs:行号 24
>    在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
>    在 MahjongAI.Models.Tile..ctor(String name) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\Models\Tile.cs:行号 24
>    在 MahjongAI.MajsoulClient.HandleInit(JToken data) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 590
>    在 MahjongAI.MajsoulClient.HandleMessage(MajsoulMessage message, Boolean forSync) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 401
>    在 MahjongAI.MajsoulClient.HandleMessage(MajsoulMessage message, Boolean forSync) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 448
>    在 MahjongAI.MajsoulClient.<OnMessage>d__54.MoveNext() 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 743
> Unexpectedly disconnected.
> Client closed.
>

**Comment by Eureka0225** [comment]
雀魂加了认证，然后这个ai雀魂的程序有点问题所以没法用了------------------ 原始邮件 ------------------
发件人: "1212march"<notifications@github.com>
发送时间: 2020年1月8日(星期三) 凌晨3:07
收件人: "zhangjk95/MahjongAI"<MahjongAI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zhangjk95/MahjongAI] 不能正常用 (#29)



登录成功之后 总是说匹配超时然后重连
 Login succeeded. MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":".lq.NotifyAccountUpdate","Json":{"update":{"activity_task":{"progresses":[{"id":1031025,"counter":1,"achieved":true,"rewarded":false},{"id":1031026,"counter":10,"achieved":true,"rewarded":false},{"id":1031027,"counter":1,"achieved":false,"rewarded":false}]}}},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.matchGame","Json":{"error":{}},"Data":null} MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}} MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.heatbeat","Json":{"error":{}},"Data":null} Game matching timed out. Unexpectedly disconnected. Client closed.Login succeeded. MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":".lq.NotifyAccountUpdate","Json":{"update":{"activity_task":{"progresses":[{"id":1031025,"counter":1,"achieved":true,"rewarded":false},{"id":1031026,"counter":10,"achieved":true,"rewarded":false},{"id":1031027,"counter":1,"achieved":false,"rewarded":false}]}}},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.matchGame","Json":{"error":{}},"Data":null} MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}} MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.heatbeat","Json":null,"Data":{"no_operation_counter":0}} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.heatbeat","Json":{"error":{}},"Data":null} Game matching timed out. Unexpectedly disconnected. Client closed.
 
咱还不信邪啊  在网页端开了一局之后  想让它重连进去 结果还是不行
 Login succeeded. Game found. Connecting... MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.FastTest.authGame","Json":null,"Data":{"account_id":8447372,"token":"c4b8d64e-621f-4cb4-8c47-c4968da822f2","game_uuid":"200108-b57d8755-e05f-4621-b063-504ec02221b1"}} MahjongAI.exe Information: 0 : Recv: {"Success":false,"Type":1,"MethodName":".lq.FastTest.authGame","Json":null,"Data":"0301000A00129903127708BBEB461099C61818CACF242215E381B5E3818FE38198E781ACE381BFE381BBE381932A0608D94F109901320E08D69A0C100518002899C61830003A0608859D011000400048005206080010EACE125206080110EFCE125206080210FECE12520608041081CF125206080710F8CE125206080810BADE1212730897FF1C10E8B51818CBCF24220CE7A59EE58C97E58D83E6ADA22A0608D94F108703321308C19A0C100418B42E28E8B51830003A02E4073A0608859D01100040004800520608001084CF125206080110FFCE125206080210F2CE12520608041082CF12520608061096CF125206080710F9CE12123A08BED0D40710E5B5181800220AE7A791E7A791E7A791782A0508F54E1000320E08C19A0C1000180028E5B51830003A0608859D01100040004800123D088CCB830410E5B51818C8CF24220A61313231326D617263682A0508F74E1014320F08C19A0C100418885928E5B51830003A0608859D011000400048001A0E8CCB830497FF1CBED0D407BBEB4620012A0C08021204080132001A021002320E8CCB830497FF1CBED0D407BBEB46"} Game continued. MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.FastTest.syncGame","Json":null,"Data":{"round_id":"-1","step":1000000}} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.FastTest.syncGame","Json":{"error":{},"is_end":false,"step":6,"game_restore":{"actions":[{"step":0,"name":"ActionMJStart","data":""},{"step":1,"name":"ActionNewRound","data":"CAAQABgAIgI1bSICNm0iAjhtIgI0cCICNXAiAjJzIgIzcyICNXMiAjdzIgI5cyICNXoiAjZ6IgI2eiICN3oyDKjDAajDAajDAajDAToNCAASAggBIKCcASjAPkAAWABiIDFkM2UwMzI3OTEyYTU4NWY5NDNiN2ExNzU1YWY2MTljaEVyAjVtegIIAHoCCAF6AggCegIIAw=="},{"step":2,"name":"ActionDiscardTile","data":"CAASAjlzGAAoADAASAA="},{"step":3,"name":"ActionDealTile","data":"CAEYRDgA"},{"step":4,"name":"ActionDiscardTile","data":"CAESAjJwGAAoADAASAA="},{"step":5,"name":"ActionDealTile","data":"CAIYQzgA"}],"passed_waiting_time":4,"game_state":1,"last_pause_time_ms":0}},"Data":null} MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.FastTest.fetchGamePlayerState","Json":null,"Data":{}} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionMJStart","Json":{},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionNewRound","Json":{"chang":0,"ju":0,"ben":0,"tiles":["5m","6m","8m","4p","5p","2s","3s","5s","7s","9s","5z","6z","6z","7z"],"scores":[25000,25000,25000,25000],"operation":{"seat":0,"operation_list":[{"type":1}],"time_add":20000,"time_fixed":8000},"liqibang":0,"al":false,"md5":"1d3e0327912a585f943b7a1755af619c","left_tile_count":69},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDiscardTile","Json":{"seat":0,"tile":"9s","is_liqi":false,"moqie":false,"zhenting":false,"is_wliqi":false},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDealTile","Json":{"seat":1,"left_tile_count":68,"zhenting":false},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDiscardTile","Json":{"seat":1,"tile":"2p","is_liqi":false,"moqie":false,"zhenting":false,"is_wliqi":false},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":2,"MethodName":"ActionDealTile","Json":{"seat":2,"left_tile_count":67,"zhenting":false},"Data":null} MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.FastTest.fetchGamePlayerState","Json":{"error":{},"state_list":[null,null,"SYNCING","READY","READY","READY"]},"Data":null} MahjongAI.exe Error: 0 : System.NullReferenceException: 未将对象引用设置到对象的实例。 在 MahjongAI.Models.Tile.<>c__DisplayClass5_0.<.ctor>b__0(KeyValuePair2 pair) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\Models\Tile.cs:行号 24
 在 System.Linq.Enumerable.First[TSource](IEnumerable1 source, Func2 predicate)
 在 MahjongAI.Models.Tile..ctor(String name) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\Models\Tile.cs:行号 24
 在 MahjongAI.MajsoulClient.HandleInit(JToken data) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 590
 在 MahjongAI.MajsoulClient.HandleMessage(MajsoulMessage message, Boolean forSync) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 401
 在 MahjongAI.MajsoulClient.HandleMessage(MajsoulMessage message, Boolean forSync) 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 448
 在 MahjongAI.MajsoulClient.d__54.MoveNext() 位置 E:\Users\1212march\Desktop\MahjongAI-master\MahjongAI\MajsoulClient.cs:行号 743
 Unexpectedly disconnected.
 Client closed.`
 
&mdash;
