### ISSUE TITLE
Unexpectedly disconnected in Majsoul

### ISSUE THREAD

**Issue by Anemen** [zhangjk95/MahjongAI#3]
自己的回合断开连接 他人的回合重新连回

**Comment by zhangjk95** [comment]
对雀魂平台的支持目前处于测试阶段，可能会有bug。对于你所提到的问题，请提供完整的log文件，如果文件太大请以链接的形式提供。

如果你使用VS，log文件在项目文件夹下的`MahjongAI\bin\Release\log.txt`。

如果你使用Docker，请先运行`docker ps -a`，找到出问题的Container ID（一般根据启动和退出时间可以判断），然后运行`docker cp CONTAINER_ID:/usr/src/app/MahjongAI/bin/Release/log.txt ~/log.txt`（例如`docker cp 58fcdcaf8a0b:/usr/src/app/MahjongAI/bin/Release/log.txt ~/log.txt`）将log文件复制到本地，之后可以在`~/log.txt`找到log文件。

**Comment by Anemen** [comment]
[log.txt](https://github.com/zhangjk95/MahjongAI/files/2702325/log.txt)

**Comment by zhangjk95** [comment]
感谢反馈，问题已修复，请git pull后再试。应该是VS版本问题导致的，如果你使用的是Docker而不是VS，请及时回复。另外，建议先开一个新号来测试，以免影响分数。如果还是无法使用，欢迎再提交反馈。
PS：由于log中含有加密后的密码，虽然理论上无法解密，但出于安全考虑目前已删除。
