### ISSUE TITLE
断线重连时有时出现新开一局的情况

### ISSUE THREAD

**Issue by huixiong806** [zhangjk95/MahjongAI#32]
如图所示，一局进行了一半，重连之后有时会直接开始新的一局
![(VAI (DT NDW{A9CTUSZN88](https://user-images.githubusercontent.com/12194875/91064768-465e7380-e662-11ea-9379-9b7b9a906c40.png)

**Comment by zhangjk95** [comment]
??NoName????????????????????????????????On Mon, Aug 24, 2020 at 08:31 orangebird <notifications@github.com> wrote:?????????????????????????????You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhangjk95** [comment]
使用NoName等临时账号是无法断线重连的，需要注册一个正式的账号才能断线重连。





在 2020-08-24 23:31:53，orangebird <notifications@github.com> 写道：


如图所示，一局进行了一半，重连之后有时会直接开始新的一局

**Comment by huixiong806** [comment]
不是NoName啊，就是注册的号。有时重连可以成功，有时失败

**Comment by zhangjk95** [comment]
天凤有五犯离场的机制，如果你一场游戏掉线超过5次的话就无法再重连。

**Comment by huixiong806** [comment]
好吧，试了一下确实是这样，很多局掉线次数都超过了5次
