### ISSUE TITLE
启动后黑屏

### ISSUE THREAD

**Issue by Moeblack** [zhangjk95/MahjongAI#34]
在visual studio 2019中打开sln，build之后控制台不输出任何文字

同文件夹log显示MahjongAI.exe Information: 0 : Send: <HELO name="NoName" tid="f0" sx="M" />
MahjongAI.exe Information: 0 : Receive: <HELO uname="%4E%6F%4E%61%6D%65" ratingscale="PF3=1.000000&PF4=1.000000&PF01C=0.582222&PF02C=0.501632&PF03C=0.414869&PF11C=0.823386&PF12C=0.709416&PF13C=0.586714&PF23C=0.378722&PF33C=0.535594&PF1C00=8.000000"/>

**Comment by zhangjk95** [comment]
???????????????????README?Moeblack <notifications@github.com>?2021?1?13? ??19:41???

?visual studio 2019???sln?build????????????

????log??MahjongAI.exe Information: 0 : Send: 

MahjongAI.exe Information: 0 : Receive: 



?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhangjk95** [comment]
请检查你是否创建了配置文件，具体步骤见README

**Comment by huixiong806** [comment]
同启动后黑屏，创建了配置文件。
log信息（ID打码）:
MahjongAI.exe Information: 0 : Send: <HELO name="IDxxxxxxxx-xxxxxxxx" tid="f0" sx="M" />
MahjongAI.exe Information: 0 : Receive: <HELO uname="%63%6F%6E%6E%65%63%74" expire="20210119" expiredays="2" ratingscale="PF3=1.000000&PF4=1.000000&PF01C=0.582222&PF02C=0.501632&PF03C=0.414869&PF11C=0.823386&PF12C=0.709416&PF13C=0.586714&PF23C=0.378722&PF33C=0.535594&PF1C00=8.000000"/> 
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />
MahjongAI.exe Information: 0 : Send: <Z />

**Comment by Moeblack** [comment]
![图片](https://user-images.githubusercontent.com/28835093/106832641-01d50a80-66cd-11eb-8c26-913dda6fe8b0.png)
这是启动后log的提示 启动后无任何文字输出
![图片](https://user-images.githubusercontent.com/28835093/106832669-0d283600-66cd-11eb-8a39-97763c0f8df0.png)
![图片](https://user-images.githubusercontent.com/28835093/106832682-15807100-66cd-11eb-9f7b-acea43c96e4e.png)
config已修改
如果此账号已登陆会正常提示login failed

**Comment by zhangjk95** [comment]
FIxed by 315693ef6435e40531bdded3c47c11f004b5328c
