### ISSUE TITLE
使用查表法提高向听数和得点的搜索速度

### ISSUE THREAD

**Issue by hyskylord** [zhangjk95/MahjongAI#37]
根据这篇文章的内容：https://www.zhihu.com/question/47124225/answer/104955538
，使用查表法大概比暴力拆解快50倍，应该可以算出三向听的得点从而大幅提高牌效。

一个使用这个方法的Lib：https://github.com/ibukisaar/JapaneseMahjong
，可以作为参考。

**Comment by zhangjk95** [comment]
感谢你的建议，向听数的计算一直用的是查表法，得点计算由于调用次数不多，所以用什么方法都不影响效率。使用的代码来自于网上，原始的链接好像已无法访问。

**Comment by hyskylord** [comment]
确实是我疏忽了，看了半天得点数的算法，没有关注向听数已经打表了= =。

**Comment by zhangjk95** [comment]
不好意思，这部分代码是从网上复制来的，可能可读性比较差。
