### ISSUE TITLE
can not login in into majsoul

### ISSUE THREAD

**Issue by LYJ19950412** [zhangjk95/MahjongAI#42]
MahjongAI.exe Information: 0 : Send: {"Success":true,"Type":0,"MethodName":".lq.Lobby.login","Json":null,"Data":{"currency_platforms":[2,6,8,10,11],"account":"******","password":"***********","reconnect":false,"random_key":"aec84347-d06c-4a94-8405-042a1926ee04","client_version":{"resource":"0.9.302.w"},"client_version_string":"web-0.9.302","gen_access_token":false,"type":0,"device":{"hardware":"pc","is_browser":true,"os":"windows","os_version":"win10","platform":"pc","sale_platform":"web","software":"Chrome"}}}
MahjongAI.exe Information: 0 : Recv: {"Success":true,"Type":1,"MethodName":".lq.Lobby.login","Json":{"error":{"code":151},"account_id":5},"Data":null}
Login failed.

the log.txt  show these,what should i do

**Comment by sparrowhe** [comment]
Please read README:

> IMPORTANT: We no longer support Majsoul starting from 0.6.64.w due to abuse of this project.

**Comment by LYJ19950412** [comment]
> Please read README:
> 
> > IMPORTANT: We no longer support Majsoul starting from 0.6.64.w due to abuse of this project.

but on 5 Oct 2021
they  Restore the support for Majsoul private rooms.(https://github.com/zhangjk95/MahjongAI/commit/a93f09784ec0fcba2fb70cef6e17ade3d8342db9)

**Comment by unStatiK** [comment]
Hi, should be fix in https://github.com/zhangjk95/MahjongAI/pull/43

**Comment by LYJ19950412** [comment]
> @LYJ19950412 Hi, should be fix in #43

thanks
