### ISSUE TITLE
cannot connect to majsoul server

### ISSUE THREAD

**Issue by tatad2** [zhangjk95/MahjongAI#5]
System.Net.WebException
  HResult=0x80131509
  Message=操作超时
  Source=System
  StackTrace:
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 System.Net.WebClient.DownloadString(String address)
   在 MahjongAI.MajsoulClient.getServerHost(String serverListUrl)
   在 MahjongAI.MajsoulClient..ctor(Config config)
   在 MahjongAI.Program.Start(Config config)
   在 MahjongAI.Program.Main(String[] args)

**Comment by zhangjk95** [comment]
Fixed by https://github.com/zhangjk95/MahjongAI/commit/a2a36697ef42feb8bd7219540ab6a5869f19edd7
